function(doc, req) {
    var head =  '<h1>' + doc._id + '</h1>';
    
    // <a href="mailto:dave@example.org">dave@example.org</a>
    var body = '<hr/><p><i>email: </i><a href="mailto:' + doc._id +'">' + doc._id +  '</a></p>';
    
    // phone, fax, notes etc
    var tail = '';
    
    if (doc.phone) {
        tail = tail + '<p><i>Phone: </i>' + doc.phone + '</p>';
    }
    
    if (doc.fax) {
        tail = tail + '<p><i>Fax: </i>' + doc.fax + '</p>';
    }
    
    if (doc.notes) {
        tail = tail + '<p><i>Notes: </i>' + doc.notes + '</p>';
    }
    
    return head + body + tail + '<hr/>';
}

///////////////////////////////////////////////////////////////////////////////
/*
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<title>Easel</title>
	<link rel="stylesheet" href="style/main.css" type="text/css">
	<link type="text/css" href="css/cupertino/jquery-ui-1.8.custom.css" rel="stylesheet" />
	<script src="/_utils/script/json2.js"></script>
	<script src="/_utils/script/jquery.js?1.3.1"></script>
	<script src="/_utils/script/jquery.couch.js?0.9.0"></script>
		<script type="text/javascript" src="js/jquery-1.4.2.min.js"></script>
		<script type="text/javascript" src="js/jquery-ui-1.8.custom.min.js"></script>
		<script type="text/javascript">
			$(function(){


				// Tabs
				$('#tabs').tabs();


				// Dialog
				$('#dialog').dialog({
					autoOpen: false,
					width: 600,
					buttons: {
						"Ok": function() {
							$(this).dialog("close");
						},
						"Cancel": function() {
							$(this).dialog("close");
						}
					}
				});

				// Dialog Link
				$('#dialog_link').click(function(){
					$('#dialog').dialog('open');
					return false;
				});

				// Datepicker
				$('#datepicker').datepicker({
					inline: true
				});

				//hover states on the static widgets
				$('#dialog_link, ul#icons li').hover(
					function() { $(this).addClass('ui-state-hover'); },
					function() { $(this).removeClass('ui-state-hover'); }
				);

			});
		</script>
		<style type="text/css">
			body{ font: 62.5% "Trebuchet MS", sans-serif; margin: 50px;}
			.headings { margin-top: 2em; }
			#dialog_link {padding: .4em 1em .4em 20px;text-decoration: none;position: relative;}
			#dialog_link span.ui-icon {margin: 0 5px 0 0;position: absolute;left: .2em;top: 50%;margin-top: -8px;}
			ul#icons {margin: 0; padding: 0;}
			ul#icons li {margin: 2px; position: relative; padding: 4px 0; cursor: pointer; float: left;  list-style: none;}
			ul#icons span.ui-icon {float: left; margin: 0 4px;}
		</style>
	</head>
	<body>
	<h1>Welcome to Easel!</h1>
	<p style="font-size: 1.3em; line-height: 1.5; margin: 1em 0; width: 50%;">Easel puts your infrastructure in the frame -
	where is it, what is it, who looks after it, and how to get hold of them. Simple.</p>

		<!-- Dialog NOTE: Dialog is not generated by UI in this demo so it can be visually styled in themeroller-->
		<h2 class="headings"></h2>
		<p><a href="#" id="dialog_link" class="ui-state-default ui-corner-all"><span class="ui-icon ui-icon-newwin"></span>Login to Easel</a></p>


		<!-- Tabs -->
		<h2 class="headings">Device Details</h2>
		<div id="tabs">
			<ul>
				<li><a href="#tab_info">Device Info</a></li>
				<li><a href="#tab_contacts">Support Contacts</a></li>
				<li><a href="#tab_location">Location</a></li>
				<li><a href="#tab_notes">Notes</a></li>
				<li><a href="#tab_inventory">Inventory</a></li>
			</ul>
			<div id="tab_info">
				<table width=90%>
					<tbody>
						<tr>
							<td><i>Device</i></td>			<td>web01.example.org</td>
							<td><i>Type</i></td>			<td>Blade Server</td>
							<td><i>Model</i></td>			<td>IBM Proliant G5</td>
						</tr>
						<tr>
							<td><i>Role</i></td>			<td>Web Server</td>
							<td><i>Status</i></td>			<td>Move to Production</td>
							<td><i>Environment</i></td>			<td>Production</td>
						</tr>
						<tr>
							<td><i>Status</i></td>			<td>Move to Production</td>
							<td><i>Environment</i></td>			<td>Production</td>
							<td><i>Security Class</i></td>	<td>Internet Facing</td>
						</tr>
						<tr>
							<td><i>Site</i></td>	<td><a href="http://rakiura/">Rakiura Datacentre</a></td>
							<td><i>Grid</i></td>			<td>Level 5 A3</td>
							<td><i>Rack</i></td>			<td>25#6</td>
						</tr>
						<tr>
							<td><i>Serial</i></td>			<td>SN478443</td>
							<td><i>Asset</i></td>			<td>#435439</td>
							<td><i>Install</i></td>			<td>2008 R2</td>
						</tr>
						<tr>
							<td><i>Purchased On</i></td>			<td>2009/10/02</td>
							<td><i>Built On</i></td>			<td>2009/11/15</td>
							<td><i>Warranty Expires</i></td>			<td>2012/10/20</td>
						</tr>
						<tr>
							<td><i>OS Coverage</i></td>		<td>7x24</td>
							<td><i>App Coverage</i></td>	<td>5x8</td>
							<td><i>Onsite Coverage</i></td>	<td>5x8</td>
						</tr>
						<tr>
							<td><i>General Managed</i></td>			<td>Y</td>
							<td><i>In Contract</i></td>			<td>Class B</td>
							<td><i>Billing</i></td>			<td>T&amp;M</td>
						</tr>
						<tr>
							<td><i>OS</i></td>			<td>Windows</td>
							<td><i>Version</i></td>			<td>2008 R2</td>
							<td><i>Release</i></td>			<td>SP3</td>
						</tr>
						<tr>
							<td><i>IP</i></td>				<td>192.168.1.24</td>
							<td><i>Subnet</i></td>			<td>10.0.0.2</td>
							<td><i>Gateway</i></td>			<td>4.2.2.1</td>
						</tr>
						<tr>
							<td><i>Backup</i></td>				<td>Y</td>
							<td><i>Last Successful</i></td>			<td>2010/05/07 14:52</td>
							<td><i></i></td>			<td></td>
						</tr>
						<tr>
							<td><i>Antivirus</i></td>				<td>Y</td>
							<td><i>Last Update</i></td>			<td>2010/05/07 12:09</td>
							<td><i></i></td>			<td></td>
						</tr>
						<tr>
							<td><i>Monitoring</i></td>				<td>Y</td>
							<td><i>Last Detected</i></td>			<td>2010/05/01 05:43</td>
							<td><i>Agents Running</i></td>			<td>Services, EventLog, AD, DNS</td>
						</tr>
						<tr>
							<td><i>Reporting</i></td>				<td>Y</td>
							<td><i>Last Update</i></td>			<td>2010/05/07 14:52</td>
							<td><i></i></td>			<td></td>
						</tr>
						<tr>
							<td><i>Patching</i></td>				<td>Y</td>
							<td><i>Last Update</i></td>			<td>2010/05/07 01:15</td>
							<td><i></i></td>			<td></td>
						</tr>
						<tr>
							<td><i>Default IP</i></td>				<td>192.168.1.24</td>
							<td><i>Subnet</i></td>			<td>192.168.1.0</td>
							<td><i>Gateway</i></td>			<td>192.168.1.1</td>
						</tr>
						<tr>
							<td><i>Console</i></td>				<td><a href="ssh://192.168.1.24/">ssh://192.168.1.24/</a></td>
							<td><i>Subnet</i></td>			<td>192.168.1.0</td>
							<td><i>Gateway</i></td>			<td>4.2.2.1</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="tab_contacts">
				<table>
					<tbody>
						<tr>
							<td><i>Service</i></td>
							<td><i>Window</i></td>
							<td><i>Provider</i></td>
						</tr>
						<tr>
							<td>Service Desk</td>
							<td>7x24</td>
							<td><a href="http://a_url.html">General Service Desk</a></td>
						</tr>
						<tr>
							<td>Event Management</td>
							<td>7x24</td>
							<td><a href="http://a_url.html">General ICT Ops NOC</a></td>
						</tr>
						<tr>
							<td>Platform Level 2</td>
							<td>7x24</td>
							<td><a href="http://a_url.html">General ICT Ops Core Infrastructure</a></td>
						</tr>
						<tr>
							<td>Backup/Restore Level 1</td>
							<td>5x8</td>
							<td><a href="http://a_url.html">General Service Desk</a></td>
						</tr>
						<tr>
							<td>Backup/Recovery Level 2</td>
							<td>7x24</td>
							<td><a href="http://a_url.html">General ICT Ops Backup/Recovery</a></td>
						</tr>
						<tr>
							<td>Database Mgmt</td>
							<td>7x24</td>
							<td><a href="http://a_url.html">Red Rocks</a></td>
						</tr>
						<tr>
							<td>Application</td>
							<td>7x24</td>
							<td><a href="http://a_url.html">General ICT Ops Middleware</a></td>
						</tr>
						<tr>
							<td>Service Delivery Manager</td>
							<td>7x24</td>
							<td><a href="http://a_url.html">Gandalf the White</a></td>
						</tr>
						<tr>
							<td>Technology Delivery Manager</td>
							<td>7x24</td>
							<td><a href="http://a_url.html">Bilbo Baggins</a></td>
						</tr>
						<tr>
							<td>Client Manager</td>
							<td>7x24</td>
							<td><a href="http://a_url.html">Sauron the Evil Eye</a></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="tab_location">location</div>
			<div id="tab_notes">notes</div>
			<div id="tab_inventory">inventory</div>
		</div>


		<!-- ui-dialog -->
		<div id="dialog" title="Login Box">
			<p>Our Easel Policy - login here.</p>
		</div>

		<!-- Datepicker -->
		<h2 class="headings">Significant Dates</h2>
		<div id="datepicker"></div>


<br/>
		<!-- Highlight / Error -->
		<h2 class="headings">Messages</h2>
		<div class="ui-widget">
			<div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;">
				<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
				<strong>Device Notes</strong> </p>
				<p>3rd party has admin access. Most device down errors come from unplanned reboots late on thursday evenings. Call to confirm then mark labour and flag job as billable.</p>
			</div>
		</div>
<br/>


		<div class="ui-widget">
			<div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;">
				<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
				<strong>Message Board</strong> </p>
				<p>20:30 planned shutdown DB for planned maintenance. Contact Bilbo Baggins for assistance.</p>
			</div>
		</div>

<br/>

		<div class="ui-widget">
			<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
				<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
				<strong>Recent Events</strong></p>
				<p>Error: attempting to clip to a position more than one buffer ahead of last clip position (a8,1524)->(14fe,7d7) </p>
			</div>
		</div>

	</body>
</html>

*/
